backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('g_detect.urls')),
]

backend/g_detect/urls.py
from django.urls import path
from . import views

app_name = 'g_detect'

urlpatterns = [
    path("home", views.home, name="home"),
    path("register", views.register, name="register"),
    path("login", views.login_user, name="login"),
    path("logout", views.logout_user, name="logout"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("add", views.add, name="add"),
    path("delete/<int:pk>/", views.delete, name="delete"),
]

backend/g_detect/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Volunteer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.CharField(max_length=100)
    phone = models.CharField(max_length=10, default="")

# Model for garbage instance
class Garbage(models.Model):
    location = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.id} : {self.location}"

class LocalGarbage(models.Model):
    id_number = models.IntegerField()
    location = models.CharField(max_length=100)
    level = models.IntegerField(
            default=1,
            validators=[
                MaxValueValidator(100),
                MinValueValidator(0)
                ]
            )
    

backend/g_detect/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .models import *
from django.http import HttpResponse, JsonResponse
from rest_framework.parsers import JSONParser
from django.views.decorators.csrf import csrf_exempt
from .serializers import GarbageSerializer

# Create your views here.
def home(request):
    return render(request, "landing/Land.html")

def register(request):
    # 0 for success 1 for fail
    if request.user.is_authenticated:
        return render(request, "dashboard/dash.html") # Dashboard

    if request.method == "POST":
        data = request.POST

        # Checking password validity
        if (data.get('password') != data.get('re_password')):
            return render(request, "Signup_page/Signup.html")

        username = data["username"]
        if username not in [i.username for i in User.objects.all()]:
            user = User.objects.create_user(
                    username=username,
                    password=data.get("password"),
                    email=data.get("email"),
                    first_name=data.get("firstname"),
                    last_name=data.get("lastname")
                )
            user.save()
            Volunteer(user=user, location=data.get("location"), phone=data.get("phone")).save()
            login(request, user)
            
            return render(request, "dashboard/dash.html", {
                'garbage': Garbage.objects.all()
            }) # Dashboard
    else:
        return render(request, "Signup_page/Signup.html")

def login_user(request):
    if request.user.is_authenticated:
        return render(request, "dashboard/dash.html", {
            'garbage': Garbage.objects.all()
        }) # Dashboard

    if request.method == "POST":
        data = request.POST
        
        user = authenticate(request, username=data["username"], password=data["password"])

        if user is not None:
            login(request, user)
            return render(request, "dashboard/dash.html", {
                'garbage': Garbage.objects.all()
            })
        
        return render(request, "Login_page/Login.html")

    return render(request, "Login_page/Login.html")

def logout_user(request):
    if request.user.is_authenticated:
        logout(request)
        return render(request, "landing/Land.html")

    return render(request, "landing/Land.html")

def dashboard(request):
    if not request.user.is_authenticated:
        return render(request, "Login_page/Login.html")
    
    return render(request, "dashboard/dash.html", {
        'garbage': Garbage.objects.all()
    })

@csrf_exempt
def add(request):
    if request.method == "POST":
        print(request.POST)
        data = JSONParser().parse(request)
        serializer = GarbageSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)

@csrf_exempt
def delete(request, pk):
    try:
        garbage = Garbage.objects.get(id=pk)
    except GarbageDoesNotExist:
        return HttpResponse(status=404)

    if request.method == "DELETE":
        garbage.delete()
        return HttpResponse(status=204)

backend/templates/Login_page/Login.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <title>Login Page</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

        <link rel="icon" type="image/x-icon" href= "{% static 'login/images/logo.png' %}">

        <link rel="stylesheet" href="{% static 'login/css/style.css' %}">
    </head>
    <body class="img js-fullheight" style="background-image: url({% static 'login/images/bg.jpg' %});">
        <section class="ftco-section">
            <div class="container">
                <div class="row justify-content-center">
                    <!-- <div class="col-md-6 text-center mb-5">
                        <h2 class="heading-section">Login #10</h2>
                        </div> -->
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-6 col-lg-4">
                        <div class="login-wrap p-0">
                            <h3 class="mb-4 text-center">Have an account?</h3>
                            <form action="{% url 'g_detect:login' %}" class="signin-form" method = "post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <input type="text" class="form-control" name= 'username' placeholder="Username" required>
                                </div>
                                <div class="form-group">
                                    <input id="password-field" type="password" name= 'password' class="form-control" placeholder="Password" required>
                                    <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="form-control btn btn-primary submit px-3">Sign In</button>
                                </div>
                                <div class="form-group d-md-flex">
                                    <div class="w-50">
                                        <label class="checkbox-wrap checkbox-primary">Remember Me
                                            <input type="checkbox" checked>
                                            <span class="checkmark"></span>
                                        </label>
                                    </div>
                                    <div class="w-50 text-md-right">
                                        <a href="#" class="page-links">Forgot Password?</a>
                                    </div>
                                </div>
                            </form>
                            <br>
                            <div class="text-center">
                                <p style="color : #fff">New Here? <a href="{% url 'g_detect:register' %}"class="page-links">Create Account</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/popper.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>

    </body>
</html>

backend/templates/Signup_page/Signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Page</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'signup/fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'signup/css/style.css' %}">
    
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static './images/logo.png' %}">

</head>
<body>
    <div class="main">
        <section class="signup">
            <!-- <img src="images/signup-bg.jpg" alt=""> -->
            <div class="container">
                <div class="signup-content">
                    <form action="{% url 'g_detect:register' %}" method="POST" id="signup-form" class="signup-form">
                        {% csrf_token %}
                        <h2 class="form-title">Create account</h2>
                        <div class="form-group">
                            <input type="text" class="form-input" name="username" id="username" placeholder="Username" required/>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-input" name="firstname" id="firstname" placeholder="First Name" required/>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-input" name="lastname" id="lastname" placeholder="Last Name" required/>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-input" name="location" id="location" placeholder="Location" required/>
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-input" name="email" id="email" placeholder="Your Email" required/>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-input" name="phone" id="phone" placeholder="Your Phone Number" required/>
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-input" name="password" id="password" placeholder="Password" required/>
                            <span toggle="#password" class="zmdi zmdi-eye field-icon toggle-password"></span>
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-input" name="re_password" id="re_password" placeholder="Repeat your password" required/>
                        </div>
                        <div class="form-group">
                            <input type="checkbox" name="agree-term" id="agree-term" class="agree-term" required/>
                            <label for="agree-term" class="label-agree-term"><span><span></span></span>I agree all statements in <a href="#" class="term-service">Terms of service</a></label>
                        </div>
                        <div class="form-group">
                            <input type="submit" name="submit" id="submit" class="form-submit" value="Sign up"/>
                            </a>
                        </div>
                    </form>
                    <p class="loginhere">
                        Have already an account ? <a href="{% url 'g_detect:login' %}" class="loginhere-link">Login here</a>
                    </p>
                </div>
            </div>
        </section>

    </div>

    <!-- JS -->
    <script src="{% static 'signup/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

backend/templates/dashboard/dash.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Dashboard</title>

        <!-- Favicon -->
        <link rel="icon" type="image/x-icon" href="{% static 'dashboard/images/logo.png' %}">
        <!-- Main css -->
        <link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}">

        <!-- Load an icon library -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

    </head>
    <body>
        <div class="container-fluid">
            <div class="row flex-nowrap">
                <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
                    <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                        <a href="#" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                            <span class="fs-5 d-none d-sm-inline">Welcome {{ user.first_name }} {{ user.last_name }}</span>
                        </a>
                        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">

                            <hr>
                            <div class="dropdown pb-4">
                                <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                                    <img src="https://github.com/mdo.png" alt="hugenerd" width="30" height="30" class="rounded-circle">
                                    <span class="d-none d-sm-inline mx-1">{{ user.first_name }}</span>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                                    <li><a class="dropdown-item" href="#">Location: {{ user.volunteer.location }}</a></li>
                                    <li><a class="dropdown-item" href="#">Settings</a></li>
                                    <li><a class="dropdown-item" href="#">Profile</a></li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="{% url 'g_detect:logout' %}">Sign out</a></li>
                                </ul>
                            </div>
                    </div>
                </div>
                <div class="col py-3">
                    <div class="col-md-10">
                        <div class="row align-items-center">

                            <div class="col">
                                <h4>Notifications</h4>
                            </div>       

                            <div class="col-7">  
                                <span class="bi bi-bell-fill noti-icon"></span>
                            </div>               
                            <table class="table table-stripped">
                                <tbody>
                                    <tr>
                                        <td><input type="checkbox" /></td>
                                        <td><i class="fa fa-star"></i></td>
                                        <td><b>Mozilla</b></td>
                                        <td><b>In celebration of women and girls everywhere</b></td>
                                        <td></td>
                                        <td>Mar 10</td>
                                    </tr>
                                    {% for i in garbage %}
                                    <tr>
                                        <td><input type="checkbox" /></td>
                                        <td><i class="fa fa-star"></i></td>
                                        <td><b>{{ i.id }}</b></td>
                                        <td><b>{{ i.location }}</b></td>
                                        <td></td>
                                        <td>Mar 10</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <body>
</html>

backend/templates/landing/Land.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Landing Page</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="fonts/material-icon/css/material-design-iconic-font.min.css">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'landing/css/style.css' %}">
    
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="./images/logo.png">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>
  <body>
  
  <nav class="navbar navbar-inverse" style="background-image:linear-gradient(#1aba1f,#1aab1e);   border: none;">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#" style="color: aliceblue;">Garbage Detection System</a>
      </div>
      <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'g_detect:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="{% url 'g_detect:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Home</a></li>
        
        <li><a href="#">About Us</a></li>
      </ul>
    </div>
  </nav>
<div class="container">
  <div class="intro-text">
        Would You like to Volunteer and help the city to be clean ? 
        <button type="button" class="btn btn-primary" id="start-btn">GET STARTED</button>
    </div>
</div>
</body>
</html>